<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <Title>UKHO Infrastructure Pipelines</Title>
    <PackageId>$(AssemblyName)</PackageId>
    <Authors>Abzu</Authors>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/UKHO/UKHO.ADDS.Infrastructure</PackageProjectUrl>
    <RepositoryUrl>https://github.com/UKHO/UKHO.ADDS.Infrastructure</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
